services:
  db:
    image: postgres
    container_name: veeniu_container
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/postgres1:/var/lib/postgresql/18/docker
    ports:
      - "6543:5432"

  cache:
    image: redis
    container_name: veeniu_redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
